export const PRIMARY_GENRES = [
  "Pop",
  "Hip-Hop / Rap",
  "Electronic / Dance",
  "Rock",
  "R&B / Soul",
  "Alternative / Indie",
  "House",
  "Techno",
  "Drum & Bass",
  "Lo-Fi / Chillhop",
  "Ambient",
  "Classical",
  "Jazz",
  "Metal",
  "Folk / Acoustic",
  "Latin / Reggaeton",
  "Afrobeat / Amapiano",
  "Reggae / Dub",
  "Country",
  "Blues",
  "Punk",
  "Synthwave / Retro",
  "Downtempo / Chill",
  "Disco / Funk",
  "Bass Music / Dubstep",
  "Trance / Psytrance",
  "Soundtrack / Cinematic",
  "Gospel / Spiritual",
  "World / Heritage",
  "Experimental / Avant-Garde",
] as const;

export type PrimaryGenre = (typeof PRIMARY_GENRES)[number];

export const GENRE_SUBGENRES_MAP: Record<string, string[]> = {
  Pop: [
    "Synth-Pop",
    "Dance-Pop",
    "Indie Pop",
    "Electropop",
    "K-Pop",
    "Art Pop",
    "Hyperpop",
    "Teen Pop",
    "Bedroom Pop",
    "Chamber Pop",
  ],
  "Hip-Hop / Rap": [
    "Trap",
    "Boom Bap",
    "Drill",
    "Melodic Rap",
    "Conscious Hip-Hop",
    "Cloud Rap",
    "East Coast",
    "West Coast",
    "Southern Hip-Hop",
    "Jazz Rap",
  ],
  "Electronic / Dance": [
    "EDM",
    "Future Bass",
    "Hardstyle",
    "Garage / UKG",
    "Electro",
    "IDM",
    "Midtempo",
    "Glitch Hop",
    "Hardcore / Gabber",
    "Breakbeat",
  ],
  Rock: [
    "Classic Rock",
    "Hard Rock",
    "Psychedelic Rock",
    "Garage Rock",
    "Progressive Rock",
    "Post-Rock",
    "Math Rock",
    "Southern Rock",
    "Stoner Rock",
    "Glam Rock",
  ],
  "R&B / Soul": [
    "Contemporary R&B",
    "Neo-Soul",
    "Motown / Classic Soul",
    "Quiet Storm",
    "Alternative R&B",
    "Funk Soul",
    "Northern Soul",
    "Gospel R&B",
    "Doo-Wop",
    "Trap Soul",
  ],
  "Alternative / Indie": [
    "Indie Rock",
    "Shoegaze",
    "Dream Pop",
    "Post-Punk",
    "Grunge",
    "Britpop",
    "Noise Rock",
    "Emo",
    "Indie Folk",
    "Goth Rock",
  ],
  House: [
    "Deep House",
    "Tech House",
    "Progressive House",
    "Melodic House",
    "Afro House",
    "Acid House",
    "Electro House",
    "Bass House",
    "French House",
    "Soulful House",
  ],
  Techno: [
    "Peak Time / Driving Techno",
    "Melodic Techno",
    "Industrial Techno",
    "Minimal Techno",
    "Dub Techno",
    "Hard Techno",
    "Acid Techno",
    "Hypnotic Techno",
    "Detroit Techno",
    "Raw / Deep Techno",
  ],
  "Drum & Bass": [
    "Liquid DnB",
    "Neurofunk",
    "Jump Up",
    "Jungle",
    "Halftime",
    "Dancefloor DnB",
    "Techstep",
    "Breakcore",
    "Deep DnB",
    "Crossbreed",
  ],
  "Lo-Fi / Chillhop": [
    "Lo-Fi Hip-Hop",
    "Chillhop",
    "Jazzhop",
    "Sleep Beats",
    "Study Beats",
    "Vaporwave",
    "Synthwave Beats",
    "Ambient Lo-Fi",
    "Lo-Fi Indie",
    "Boom Bap Lo-Fi",
  ],
  Ambient: [
    "Drone",
    "Dark Ambient",
    "Space Ambient",
    "Healing / Meditation",
    "Soundscape",
    "Field Recordings",
    "Biomusic / Nature",
    "Isolationism",
    "Illbient",
    "Warm Ambient",
  ],
  Classical: [
    "Baroque",
    "Classical Era",
    "Romantic",
    "Modern Classical",
    "Chamber Music",
    "Opera",
    "Choral",
    "Minimalism",
    "Renaissance",
    "Symphonic",
  ],
  Jazz: [
    "Bebop",
    "Cool Jazz",
    "Modal Jazz",
    "Fusion",
    "Smooth Jazz",
    "Vocal Jazz",
    "Gypsy Jazz",
    "Hard Bop",
    "Free Jazz",
    "Latin Jazz",
  ],
  Metal: [
    "Heavy Metal",
    "Thrash Metal",
    "Death Metal",
    "Black Metal",
    "Metalcore",
    "Doom Metal",
    "Power Metal",
    "Nu-Metal",
    "Sludge Metal",
    "Progressive Metal",
  ],
  "Folk / Acoustic": [
    "Contemporary Folk",
    "Singer-Songwriter",
    "Traditional Folk",
    "Indie Folk",
    "Americana",
    "Bluegrass",
    "Celtic Folk",
    "Fingerstyle Guitar",
    "Anti-Folk",
    "Appalachian Folk",
  ],
  "Latin / Reggaeton": [
    "Reggaeton",
    "Latin Pop",
    "Bachata",
    "Salsa",
    "Trap Latino",
    "Bossa Nova",
    "Cumbia",
    "Merengue",
    "Flamenco Pop",
    "Samba",
  ],
  "Afrobeat / Amapiano": [
    "Afrobeats",
    "Amapiano",
    "Afro-Pop",
    "Afro-Fusion",
    "Highlife",
    "Kwaito",
    "Gqom",
    "Kizomba / Zouk",
    "Coupé-Décalé",
    "Bongo Flava",
  ],
  "Reggae / Dub": [
    "Roots Reggae",
    "Dub",
    "Dancehall",
    "Ska",
    "Rocksteady",
    "Lovers Rock",
    "Raggamuffin",
    "Dubstep Reggae",
    "Mento",
    "Sound System Reggae",
  ],
  Country: [
    "Contemporary Country",
    "Outlaw Country",
    "Country Pop",
    "Americana",
    "Honky Tonk",
    "Bluegrass",
    "Country Rock",
    "Bakersfield Sound",
    "Alt-Country",
    "Western Swing",
  ],
  Blues: [
    "Delta Blues",
    "Chicago Blues",
    "Electric Blues",
    "Texas Blues",
    "Jump Blues",
    "Contemporary Blues",
    "Country Blues",
    "Soul Blues",
    "Piedmont Blues",
    "Blues Rock",
  ],
  Punk: [
    "Pop-Punk",
    "Hardcore Punk",
    "Post-Punk",
    "Ska Punk",
    "Skate Punk",
    "Anarcho-Punk",
    "Emo / Screamo",
    "Crust Punk",
    "Riot Grrrl",
    "Garage Punk",
  ],
  "Synthwave / Retro": [
    "Darksynth",
    "Chillwave",
    "Outrun",
    "Synthpop",
    "Vaporwave",
    "Retrowave",
    "Future Funk",
    "Dreamwave",
    "Spacewave",
    "Cyberpunk / Industrial Synth",
  ],
  "Downtempo / Chill": [
    "Trip-Hop",
    "Chillout",
    "Psybient",
    "Illbient",
    "Lounge",
    "Nu-Jazz",
    "Balearic Beat",
    "Ambient Dub",
    "Coffeehouse Chill",
    "Slowcore",
  ],
  "Disco / Funk": [
    "Nu-Disco",
    "Classic Disco",
    "P-Funk",
    "Boogie",
    "Funk Rock",
    "Soul Funk",
    "Italo Disco",
    "Electro Funk",
    "Space Disco",
    "G-Funk (Instrumental)",
  ],
  "Bass Music / Dubstep": [
    "Dubstep",
    "Riddim",
    "Tearout",
    "Future Bass",
    "Trap / Bass",
    "Leftfield Bass",
    "Midtempo Bass",
    "Melodic Dubstep",
    "Wave",
    "Footwork / Juke",
  ],
  "Trance / Psytrance": [
    "Uplifting Trance",
    "Progressive Trance",
    "Psytrance",
    "Goa Trance",
    "Vocal Trance",
    "Tech Trance",
    "Full-On Psytrance",
    "Darkpsy",
    "Euro-Trance",
    "Hard Trance",
  ],
  "Soundtrack / Cinematic": [
    "Film Score",
    "Video Game Soundtrack",
    "Trailer Music",
    "Orchestral Score",
    "Anime OST",
    "Epic Instrumental",
    "Dark Cinematic",
    "Chamber Film Music",
    "Electronic Score",
    "Fantasy / Adventure",
  ],
  "Gospel / Spiritual": [
    "Contemporary Christian",
    "Traditional Gospel",
    "Urban Contemporary Gospel",
    "Praise & Worship",
    "Spirituals",
    "Southern Gospel",
    "Christian Hip-Hop",
    "Gospel Blues",
    "Choral Hymns",
    "Meditative Chant",
  ],
  "World / Heritage": [
    "Flamenco",
    "Middle Eastern",
    "Celtic",
    "Indian Classical",
    "Afro-Cuban",
    "Traditional Asian",
    "Nordic Folk",
    "Balkan Folk",
    "Polynesian / Pacific",
    "Andean / Indigenous",
  ],
  "Experimental / Avant-Garde": [
    "Noise",
    "Glitch",
    "Industrial",
    "Musique Concrète",
    "Free Improvisation",
    "Microsound",
    "Art Pop",
    "Microtonal",
    "Sound Collage",
    "Deconstructed Club",
  ],
};

export const CATALOG_MOODS = [
  "Energetic",
  "Chill / Relaxed",
  "Deep Focus",
  "Dark / Moody",
  "Melancholic",
  "Uplifting / Happy",
  "Romantic / Sensual",
  "Aggressive / Intense",
  "Dreamy / Ethereal",
  "Groovy / Funky",
  "Peaceful / Meditative",
  "Cinematic / Epic",
] as const;

export type CatalogMood = (typeof CATALOG_MOODS)[number];

export function matchFuzzyGenre(rawGenre?: string | null): {
  primaryGenre?: PrimaryGenre;
  subGenre?: string;
} {
  if (!rawGenre || typeof rawGenre !== "string") return {};

  const clean = rawGenre.trim().toLowerCase();
  if (!clean) return {};

  // 1. Direct match with primary genre
  for (const primary of PRIMARY_GENRES) {
    if (primary.toLowerCase() === clean) {
      return { primaryGenre: primary };
    }
  }

  // 2. Direct match with subgenres
  for (const [primary, subgenres] of Object.entries(GENRE_SUBGENRES_MAP)) {
    for (const sub of subgenres) {
      if (sub.toLowerCase() === clean) {
        return { primaryGenre: primary as PrimaryGenre, subGenre: sub };
      }
    }
  }

  // 3. Keyword / partial matching
  for (const [primary, subgenres] of Object.entries(GENRE_SUBGENRES_MAP)) {
    for (const sub of subgenres) {
      const subLower = sub.toLowerCase();
      if (clean.includes(subLower) || subLower.includes(clean)) {
        return { primaryGenre: primary as PrimaryGenre, subGenre: sub };
      }
    }
  }

  for (const primary of PRIMARY_GENRES) {
    const primaryLower = primary.toLowerCase();
    const parts = primaryLower.split("/").map((p) => p.trim());
    for (const part of parts) {
      if (clean.includes(part) || part.includes(clean)) {
        return { primaryGenre: primary as PrimaryGenre };
      }
    }
  }

  return {};
}
