/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminVerificationRouteImport } from './routes/admin.verification'
import { Route as AlbumsIdOrSlugRouteImport } from './routes/albums.$idOrSlug'
import { Route as ArtistsIndexRouteImport } from './routes/artists.index'
import { Route as ArtistsIdOrSlugRouteImport } from './routes/artists.$idOrSlug'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as PlaylistsIndexRouteImport } from './routes/playlists.index'
import { Route as PlaylistsIdRouteImport } from './routes/playlists.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/admin/subscriptions',
  path: '/admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/admin/verification',
  path: '/admin/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsIdOrSlugRoute = AlbumsIdOrSlugRouteImport.update({
  id: '/albums/$idOrSlug',
  path: '/albums/$idOrSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIdOrSlugRoute = ArtistsIdOrSlugRouteImport.update({
  id: '/artists/$idOrSlug',
  path: '/artists/$idOrSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIndexRoute = PlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIdRoute = PlaylistsIdRouteImport.update({
  id: '/playlists/$id',
  path: '/playlists/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/studio': typeof StudioRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/albums/$idOrSlug': typeof AlbumsIdOrSlugRoute
  '/artists/$idOrSlug': typeof ArtistsIdOrSlugRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/playlists/$id': typeof PlaylistsIdRoute
  '/artists/': typeof ArtistsIndexRoute
  '/playlists/': typeof PlaylistsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/studio': typeof StudioRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/albums/$idOrSlug': typeof AlbumsIdOrSlugRoute
  '/artists/$idOrSlug': typeof ArtistsIdOrSlugRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/playlists/$id': typeof PlaylistsIdRoute
  '/artists': typeof ArtistsIndexRoute
  '/playlists': typeof PlaylistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/studio': typeof StudioRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/albums/$idOrSlug': typeof AlbumsIdOrSlugRoute
  '/artists/$idOrSlug': typeof ArtistsIdOrSlugRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/playlists/$id': typeof PlaylistsIdRoute
  '/artists/': typeof ArtistsIndexRoute
  '/playlists/': typeof PlaylistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/studio'
    | '/verify-email'
    | '/admin/subscriptions'
    | '/admin/verification'
    | '/albums/$idOrSlug'
    | '/artists/$idOrSlug'
    | '/oauth/callback'
    | '/playlists/$id'
    | '/artists/'
    | '/playlists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/studio'
    | '/verify-email'
    | '/admin/subscriptions'
    | '/admin/verification'
    | '/albums/$idOrSlug'
    | '/artists/$idOrSlug'
    | '/oauth/callback'
    | '/playlists/$id'
    | '/artists'
    | '/playlists'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/studio'
    | '/verify-email'
    | '/admin/subscriptions'
    | '/admin/verification'
    | '/albums/$idOrSlug'
    | '/artists/$idOrSlug'
    | '/oauth/callback'
    | '/playlists/$id'
    | '/artists/'
    | '/playlists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  StudioRoute: typeof StudioRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  AlbumsIdOrSlugRoute: typeof AlbumsIdOrSlugRoute
  ArtistsIdOrSlugRoute: typeof ArtistsIdOrSlugRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  PlaylistsIdRoute: typeof PlaylistsIdRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/admin/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$idOrSlug': {
      id: '/albums/$idOrSlug'
      path: '/albums/$idOrSlug'
      fullPath: '/albums/$idOrSlug'
      preLoaderRoute: typeof AlbumsIdOrSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/': {
      id: '/artists/'
      path: '/artists'
      fullPath: '/artists/'
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$idOrSlug': {
      id: '/artists/$idOrSlug'
      path: '/artists/$idOrSlug'
      fullPath: '/artists/$idOrSlug'
      preLoaderRoute: typeof ArtistsIdOrSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/playlists'
      fullPath: '/playlists/'
      preLoaderRoute: typeof PlaylistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$id': {
      id: '/playlists/$id'
      path: '/playlists/$id'
      fullPath: '/playlists/$id'
      preLoaderRoute: typeof PlaylistsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  StudioRoute: StudioRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  AlbumsIdOrSlugRoute: AlbumsIdOrSlugRoute,
  ArtistsIdOrSlugRoute: ArtistsIdOrSlugRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  PlaylistsIdRoute: PlaylistsIdRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
